name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn release
        env:
          DEBUG: "*"
          GH_TOKEN: ${{ secrets.GH_PAT }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
